check:
  name: Check Internet Health
  description: >
    Performs a comprehensive check of internet connectivity including DNS resolution,
    TCP port connectivity, and HTTP connectivity tests.
  fields: {}
  target: {}
