name: HACS Action

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"  # Note: Fixed the cron syntax (there was a typo with **)

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
